In [2]:
import cv2
import numpy as np
import os

In [3]:
img = cv2.imread("images/hehe.jpg")  #read image
print(img)   # display the image's pixel values as a multi-dimensional NumPy array

#NOTE : OPENCV HAS IMAGES STORED IN BGR FORMAT [GENERALLY IMAGES ARE IN RGB]

#imread contains a second parameter flag which can be set to 0 to diplay image as black-white [BY DEFAULT flag is set to 1]
#this black and white is known as grayscale image

bw_img = cv2.imread("images/hehe.jpg",0)
cv2.imshow("BlackWhite",bw_img)

cv2.imshow("New",img)  #show image
if img is None:
    print("Failed to load image.")
else:
    print("Image loaded successfully.")
cv2.waitKey(0) #image frame wait time in ms  when set to 0 press any key on keyboard
cv2.destroyWindow("New") #destroy the specified window
cv2.destroyAllWindows()  # destroy all windows


[[[246 218 201]
  [244 217 203]
  [244 215 208]
  ...
  [232 214 203]
  [231 213 202]
  [230 212 201]]

 [[247 219 202]
  [245 218 204]
  [245 216 209]
  ...
  [234 216 205]
  [233 215 204]
  [232 214 203]]

 [[248 220 203]
  [246 219 205]
  [245 216 209]
  ...
  [231 213 202]
  [230 212 201]
  [230 212 201]]

 ...

 [[221 225 166]
  [232 228 179]
  [253 232 204]
  ...
  [218 199 192]
  [226 207 200]
  [235 216 209]]

 [[180 199 136]
  [214 224 177]
  [233 226 207]
  ...
  [219 200 193]
  [227 208 201]
  [236 217 210]]

 [[170 197 133]
  [214 233 184]
  [229 228 214]
  ...
  [208 189 182]
  [216 197 190]
  [225 206 199]]]
Image loaded successfully.


error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:1261: error: (-27:Null pointer) NULL window: 'New' in function 'cvDestroyWindow'


In [27]:
img.shape # three element tuple where first two are dimension Height x Width and third is no of color channel

(460, 460, 3)

In [29]:
#Resizing/Scaling the Image 
resized_img = cv2.resize(img,(500,500))
cv2.imshow("Resize",resized_img)
cv2.waitKey(0) #image frame wait time in ms  when set to 0 press any key on keyboard
cv2.destroyWindow("Resize")

In [31]:
#Rotate the image

m = cv2.getRotationMatrix2D((250,250),90,1)
rotated_img = cv2.warpAffine(resized_img,m,(500,500))

cv2.imshow("New Window",rotated_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
h = np.hstack((resized_img,resized_img)) # 2 numpy array ko merge krke single array bana deta h
v = np.vstack((resized_img,resized_img)) #hstack = horizontal, vstack =  vertical
cv2.imshow("Horizontal",h)
cv2.imshow("Vertical",v)
cv2.waitKey(0) #image frame wait time in ms  when set to 0 press any key on keyboard
cv2.destroyAllWindows()

In [35]:
# now to display image as matix format like in grid view
h = np.hstack((resized_img,resized_img)) # 2 numpy array ko merge krke single array bana deta h
v = np.vstack((h,h)) #horizontally jo merged aai unko vertically bhi merge kr diya
cv2.imshow("Grid",v)
cv2.waitKey(0) #image frame wait time in ms  when set to 0 press any key on keyboard
cv2.destroyAllWindows()

In [37]:
#sideshow of multiple images in a folder
list_name = os.listdir("C:\\Users\\satya\\OneDrive\\Desktop\\ww_img")
for name in list_name:
    img_path = "C:\\Users\\satya\\OneDrive\\Desktop\\ww_img\\" + name
    img = cv2.imread(img_path)  #read image
    img = cv2.resize(img,(500,600))
    cv2.imshow("New Window",img)
    cv2.waitKey(1000)
cv2.destroyAllWindows()

error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'


In [ ]:
#Text over Image 

img_get = cv2.imread(r"C:\Users\satya\OneDrive\Desktop\hehe.jpg")
img_get = cv2.resize(img_get,(500,600))

txt = cv2.putText(img_get, "Test Text", (50,150), cv2.FONT_HERSHEY_DUPLEX, 3, (255,0,0), 5, cv2.LINE_8, False)

cv2.imshow("Window",txt)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#Draw line over a image

new_img = cv2.line(img = resized_img, pt1 = (190,60), pt2 = (320,60), color = (0,255,0),thickness = 4,lineType = 4)


cv2.imshow("Window",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#Draw  Rectangle over a image


new_img2 = cv2.rectangle(img = resized_img, pt1 = (190,0), pt2 = (320,150), color = (0,255,0),thickness = 4,lineType = 4)


cv2.imshow("Window",new_img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#Draw  Circle over a image


new_img3 = cv2.circle(img = resized_img, center = (255,75), radius = 100, color = (0,255,0),thickness = 4,lineType = 16)

#thickness = -1 will fill the entire circle

cv2.imshow("Window",new_img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#Draw  Ellipse over a image

new_img4 = cv2.ellipse(img = resized_img, center = (255,75), axes = (50,80), angle = 30,startAngle = 0, endAngle = 360, color = (0,255,0),thickness = 4,lineType = 16)

#thickness = -1 will fill the entire ellipse

cv2.imshow("Window",new_img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#Draw  Polygon over a image

new_img4 = cv2.polylines(img = resized_img, 
                        pts = [np.array([[250,0],[200,30],[200,100],[260,150],[320,100],[300,40]])],
                        isClosed = True, color = (0,255,0),thickness = 4,lineType = 16)

#thickness = -1 will fill the entire ellipse

cv2.imshow("Window",new_img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

# note that the drawing functions like text,line, circle,rectangle etc overwrites the original image passed so storing it in a new variable doesn't really matters, if you want to save the original image from modification then first create the copy of the image and then work on it

In [ ]:
#Edge Detection

img = cv2.imread("images/hehe.jpg")
img = cv2.resize(img,(500,500))
print(img.shape)

new = cv2.Canny(img,150,150)

#more the value of threshold in the canny function lesser the detailing
print(new.shape)

cv2.imshow("Image",img)
cv2.imshow("New Image",new)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#Blurring Image 
#Image blurring is done in 3 ways-Gaussian Blur,Median Blur,Bilateral Blur

In [ ]:

img = cv2.imread("images/hehe.jpg")
img = cv2.resize(img,(300,300))

g = cv2.GaussianBlur(img,(7,7),0)
m = cv2.medianBlur(img,3)
b = cv2.bilateralFilter(img,9,75,75)

h = np.hstack((img,g,m,b))
cv2.imshow("Image",h)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#Border on an image
#Many types of border

img = cv2.imread("images/hehe.jpg")
img = cv2.resize(img,(300,300))

img1 = cv2.copyMakeBorder(img,20,20,20,20,
                          borderType = cv2.BORDER_CONSTANT,
                          dst = None, value = 2
                         )
img1 = cv2.resize(img1,(300,300))

img2 = cv2.copyMakeBorder(img,20,20,20,20,
                          borderType = cv2.BORDER_REFLECT,
                          dst = None, value = 2
                         )
img2 = cv2.resize(img2,(300,300))

img3 = cv2.copyMakeBorder(img,20,20,20,20,
                          borderType = cv2.BORDER_REPLICATE,
                          dst = None, value = 2
                         )
img3 = cv2.resize(img1,(300,300))

h = np.hstack((img,img1,img2,img3))
cv2.imshow("Image",h)
cv2.waitKey(0)
cv2.destroyAllWindows()



In [ ]:
#Saving an image using imwrite

cv2.imwrite("images/save1.png",h)

In [ ]:
# color cvt

img = cv2.imread("images/hehe.jpg")  #read image
img = cv2.resize(img,(500,500))

new = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cv2.imshow("Window",img)
cv2.imshow("New Window",new)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#crop image


img = cv2.imread("images/hehe.jpg")  #read image
img = cv2.resize(img,(500,500))

print(img.shape) #shape
print(img) #pixels of image

#img[y1:y2 , x1:x2]

crop = img[200:400  ,:]

cv2.imshow("Crop Image",crop)

cv2.imshow("Window",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#create blank image

img = cv2.imread("images/hehe.jpg")  #read image
img = cv2.resize(img,(500,500))
print(img.shape) #shape
print(img) #pixels of image

#blank image could either be full black or full white

new = np.ones((500,500,3),np.uint8)*255  #white image
new2 = np.zeros((500,500,3),np.uint8)*255  #black image

cv2.imshow("New Image",new)
cv2.imshow("New Image",new2)

cv2.imshow("Window",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#color  picker  &  trackbar [getTrackbarPos & createTrackbar]

def func(x):
    pass

img = np.zeros((500,500,3),np.uint8)*255  #black image
cv2.namedWindow("color")

cv2.createTrackbar("R","color",0,255,func)
cv2.createTrackbar("G","color",0,255,func)
cv2.createTrackbar("B","color",0,255,func)

while True:
    cv2.imshow("color",img)
    if cv2.waitKey(1) & 0xff == ord('p'):
        break
    r = cv2.getTrackbarPos("R","color")
    g = cv2.getTrackbarPos("G","color")
    b = cv2.getTrackbarPos("B","color")
    
    img[:] = [b,g,r]

cv2.destroyAllWindows()  

In [ ]:
#Region of Interest
